export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_ROUNDS_SUCCESS = 'REQUEST_ROUNDS_SUCCESS';
export const REQUEST_ROUNDS_FAILED = 'REQUEST_ROUNDS_FAILED';
export const REQUEST_ROUNDS_PENDING = 'REQUEST_ROUNDS_PENDING';